### ISSUE TITLE
First row not draggable when antd showHeader={false}

### ISSUE THREAD

**Issue by menberg** [raisezhang/react-drag-listview#11]
Hi there!

When working with [Ant Design's Table Component](https://ant.design/components/table/ ), the first row is not draggable when the header row is hidden with `showHeader={false}`

https://codepen.io/anon/pen/pKVKrL

Is there a way to fix it?

**Comment by raisezhang** [comment]
参考下这个 Issue：  https://github.com/raisezhang/react-drag-listview/issues/9    

Demo： https://codepen.io/raisezhang/pen/rKNMgZ       添加 showHeader 属性，看下效果
