### ISSUE TITLE
IE9 support?

### ISSUE THREAD

**Issue by tonypig93** [raisezhang/react-drag-listview#18]
it seems cannot work under IE9

**Comment by raisezhang** [comment]
Can you paste some error logs?     Thanks

**Comment by Mathround** [comment]
> Can you paste some error logs? Thanks

Dragging Ant-Design Table Columns
你好，我现在用的是上面这个例子，假如我想把第一列固定并且禁止用户拖动，请问需要该怎么实现呢

**Comment by tonypig93** [comment]
> Can you paste some error logs? Thanks

没有报错，我发现IE9下直接拖拽不成功，必须选中某些文字，然后点击选中部分才能拖拽，有点奇怪

**Comment by raisezhang** [comment]
@Mathround   不建议在当前 Issue 中添加新的问题，这样对有相同问题的人不太好搜索~  

你可以修改  nodeSelector  参数， 它是支持 cssQuery 的，比如   ```th:not(:nth-child(1))```  来解决你的问题

**Comment by Mathround** [comment]
> @Mathround 不建议在当前 Issue 中添加新的问题，这样对有相同问题的人不太好搜索~
> 
> 你可以修改 nodeSelector 参数， 它是支持 cssQuery 的，比如 `th:not(:nth-child(1))` 来解决你的问题



> @Mathround 不建议在当前 Issue 中添加新的问题，这样对有相同问题的人不太好搜索~
> 
> 你可以修改 nodeSelector 参数， 它是支持 cssQuery 的，比如 `th:not(:nth-child(1))` 来解决你的问题

嗯，谢谢哈

**Comment by raisezhang** [comment]
nodeSelector: "th",
handleSelector: "th:not(:nth-child(1))"

可以试下这两个属性

**Comment by Mathround** [comment]
> nodeSelector: "th",
> handleSelector: "th:not(:nth-child(1))"
> 
> 可以试下这两个属性

你好，我发现个问题，在浏览器网页是正常可以进行拖拽的，如果嵌入到客户端里面，发现就不能正常拖拽了，拖拽没效果

**Comment by raisezhang** [comment]
@Mathround “嵌入到客户端” 是 PC 还是 App 里面？  

如果 PC 的话看是不是 IE 小于 IE10 的版本？
App的话 目前还不支持移动端

**Comment by Mathround** [comment]
> @Mathround “嵌入到客户端” 是 PC 还是 App 里面？
> 
> 如果 PC 的话看是不是 IE 小于 IE10 的版本？
> App的话 目前还不支持移动端

是pc的客户端，这个客户端是我们公司自己的，就是前端页面写好直接嵌入到里面去

**Comment by Mathround** [comment]
> @Mathround “嵌入到客户端” 是 PC 还是 App 里面？
> 
> 如果 PC 的话看是不是 IE 小于 IE10 的版本？
> App的话 目前还不支持移动端

你好，是pc的客户端，这个客户端是公司用的，基于chrome内核，版本是49.0.1.0

**Comment by raisezhang** [comment]
可以贴下相关错误信息么？   或者你那边调试看下是啥问题？  然后来个 PR ？

**Comment by raisezhang** [comment]
没啥问题我先 Close 了 ，  如有问题可以新开个 issue ~     多谢~

**Comment by Mathround** [comment]
> 没啥问题我先 Close 了 ， 如有问题可以新开个 issue ~ 多谢~

好的
