### ISSUE TITLE
Drop target to closest line

### ISSUE THREAD

**Issue by Studio384** [raisezhang/react-drag-listview#24]
As seen [in the demo](https://raisezhang.github.io/react-drag-listview/examples/simple.html), when you start dragging (for example) `rows4`, as soon as you reach `rows3` the droptarget will be between the second and third item, when moving into `rows2` the drop targets jumps inbetween the first and second item. The same happens when going down only now the drop target will be below the current row you hover over.

Is there a way to make the drop target stay on the closest line, so that, for example, if you're holding the draggable row in the bottom 50% of `rows2` the droptarget is between the second and third row, and when in the upper 50% the droptarget is between the first and second row.

**Comment by raisezhang** [comment]
Currently, the selected move is driven by the native ```ondragenter``` event.

For example, if you want to move rows3 to rows2,  if rows3 dragenter the rows2, there will be lines at the top of rows2;  if rows2 moves to rows3, there will be lines at the bottom of rows3.

So...   50% of the granularity is not easy to achieve~   

If you have a good idea, welcome to submit a PR!

Thanks~
