### ISSUE TITLE
Antd table not work with column fixed

### ISSUE THREAD

**Issue by MrChe** [raisezhang/react-drag-listview#27]
If add column fixed to Antd table fixed column, reordering not work

**Comment by raisezhang** [comment]
Can you provide an online demo that can be reproduced?  

 [CodePen](https://codepen.io/raisezhang/pen/MoMoyz)

**Comment by LynxUA** [comment]
I have the same problem.
@raisezhang, here is a link to Codesandbox (just remove the fixed: true and it will work fine):
https://codesandbox.io/s/antd3-table-with-columns-drag-drop-1f1m5

**Comment by raisezhang** [comment]
https://codesandbox.io/s/antd3-table-with-columns-drag-drop-tk36e

``` javascript
this.dragProps = {
  onDragEnd(fromIndex, toIndex) {
    const columns = [...that.state.columns];
    const item = columns.splice(fromIndex, 1)[0];
    columns.splice(toIndex, 0, item);
    that.setState({
      columns
    });
  },
  nodeSelector: "th"
};
```
