### ISSUE TITLE
Typings needed

### ISSUE THREAD

**Issue by boufran1** [raisezhang/react-drag-listview#29]
Hi,

I would like to included your package in my react app. However I would like to keep the compiler option noImplicitAny to true. Would it be possible to create a typings file for your package?

**Comment by raisezhang** [comment]
You can try to generate ```.d.ts``` in this way.
https://github.com/microsoft/dts-gen

**Comment by boufran1** [comment]
Alright thank your very much

**Comment by damiangreen** [comment]
Running `dts-gen -m react-drag-listview` on this generates error:
`namespace prototype` is duplicated 
and warnings for `isMounted` and `replaceState`

**Comment by raisezhang** [comment]
Can you succeed on your project?  @boufran1

**Comment by boufran1** [comment]
I haven't tried yet. I took down the URL you gave me and though to go back to it when I had time. Work has me shift my focus on something else.
