### ISSUE TITLE
when will be ready to support for draging and dropping rows in diffirent Ant-Design Tables?

### ISSUE THREAD

**Issue by poryzhao** [raisezhang/react-drag-listview#3]
As described in the title,  I get several tables in one container, for every row in one table, it can be dragged and dropped in its own table, and it can be dropped to another table as well.  Can this be supported soon?

**Comment by raisezhang** [comment]
There is a temporary solution:
Use  [Antd Transfer](https://ant.design/components/transfer/) and drag components . Of course, the table data needs to be small, need to simulate the table style！

If not realized, I will be in mid-September to achieve this case!

**Comment by raisezhang** [comment]
e...  I will close this issue,  if more user has this  demand~   Thanks
