### ISSUE TITLE
react-drag-listview can provide one Properties that can let antd table column cant't be drag?

### ISSUE THREAD

**Issue by Catsbe** [raisezhang/react-drag-listview#34]

**Comment by Catsbe** [comment]
I can't  found this properties in you github or the source code.

**Comment by raisezhang** [comment]
You can temporarily modify the value of nodeselector or handleselector.
Set a cssQuery that does not exist

**Comment by Catsbe** [comment]
I took your advice，set ant table colums className property equal to dragProps nodeSelector property 。And It's working ，thank’s a lot
