### ISSUE TITLE
ReactDragListView.DragColumn在antd 4.x 版本中cloumns数据改变了，但是表头渲染没变化

### ISSUE THREAD

**Issue by fengyun2** [raisezhang/react-drag-listview#37]

**Comment by raisezhang** [comment]
有可复现的 Demo 么？   按理说  DragListView 仅仅是在 Table 外面包了一层，不会对 Table 的渲染有影响

**Comment by fengyun2** [comment]
@raisezhang 直接打开你们官方的demo即可重现：https://codepen.io/raisezhang/pen/MoMoyz

**Comment by raisezhang** [comment]
已修复，多谢反馈
