### ISSUE TITLE
How to use in function component?

### ISSUE THREAD

**Issue by eparizzi** [raisezhang/react-drag-listview#38]
I'm trying to use this library with an Antd Table in a function component but I can't get it working.

Here's the Antd Table example converted into a function component using `setState` hook.
https://codesandbox.io/s/react-drag-listview-in-functional-component-xqnfx

**Comment by raisezhang** [comment]
https://codesandbox.io/s/react-drag-listview-in-functional-component-7eyf5

``` javascript
const dragProps = {
  onDragEnd(fromIndex, toIndex) {
    console.log(`dragged from ${fromIndex} to ${toIndex}`);
    const newColumns = [...columns];
    const item = newColumns.splice(fromIndex, 1)[0];
    newColumns.splice(toIndex, 0, item);
    setColumns(newColumns);
  },
  nodeSelector: "th"
};
```
