### ISSUE TITLE
I got a error when page loading using react-drag-listview

### ISSUE THREAD

**Issue by farisnceit** [raisezhang/react-drag-listview#39]
./node_modules/react-drag-listview/es/ReactDragListView.js
Module not found: Can't resolve 'babel-runtime/helpers/classCallCheck' in '.\node_modules\react-drag-listview\es'

can you help

**Comment by realripley00** [comment]
@farisnceit Do you remember how you resolved this? I am getting the same error. I tried installing babel-runtime, and it still doesn't seem to work
