### ISSUE TITLE
Table的children

### ISSUE THREAD

**Issue by songhanlin** [raisezhang/react-drag-listview#4]
ant的table标签还有children, 就是类似在table中有个tree的样式, 这种情况就导致了index并不是我想要的, 可不可以获取在table中的rowinfo, 这样我可以根据他们不同的级别, 以及位置做不一样的操作

**Comment by raisezhang** [comment]
可以通过重写  ```getDomIndex```  方法来实现一下；

通过 Table 行的 class 来判断索引，我看了下是  ```ant-table-row```  这个就行

**Comment by raisezhang** [comment]
没啥问题先 close 了
