### ISSUE TITLE
Error in Firefox: Uncaught TypeError: target.parentNode is null

### ISSUE THREAD

**Issue by whenmoon** [raisezhang/react-drag-listview#40]
I am getting to following error:

```javascript
Uncaught TypeError: target.parentNode is null
    onDragEnd ReactDragListView.js:113
    onMouseDown ReactDragListView.js:61
    React 15
    unstable_runWithPriority scheduler.development.js:643
    React 25
    render render.js:74
    render render.js:73
    _callee$ render.js:165
    Babel 3
    asyncGeneratorStep render.js:48
    _next render.js:50
    _asyncToGenerator render.js:50
```
This is happening on drag end and only in Firefox, not Chrome. What could be the reason for this? Thanks

**Comment by raisezhang** [comment]
I tested demo in Firebox and didn't get this error

[https://raisezhang.github.io/react-drag-listview/examples/simple.html](https://raisezhang.github.io/react-drag-listview/examples/simple.html)

Or send a demo that can be reproduced
