### ISSUE TITLE
Not working on Touchable Screen

### ISSUE THREAD

**Issue by Azshar** [raisezhang/react-drag-listview#42]
Hello,not working on mobile and tablet devices

**Comment by lijinke666** [comment]
+1

**Comment by raisezhang** [comment]
OK, I see. I'll deal with this problem recently

**Comment by matteocollina** [comment]
@raisezhang any news?

**Comment by rajat-sf** [comment]
@raisezhang +1

**Comment by babytiger0929** [comment]
any update on here?

**Comment by Anujkapasia** [comment]
Nothing yet?

**Comment by raisezhang** [comment]
Sorry for taking so long to fix this. **Drag and drop on mobile devices is now supported.**

Documentation has been updated: [use-on-mobile-touch-devices](https://github.com/raisezhang/react-drag-listview#use-on-mobile-touch-devices).

This is an example: https://codepen.io/raisezhang/pen/wvpVbQO
