### ISSUE TITLE
Not installing 

### ISSUE THREAD

**Issue by andrewkazan** [raisezhang/react-drag-listview#43]
Hi man!:) I was installed this package through our system. But it's throw me error 
"  'react-drag-listview@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)"

Do you know how solve problem?

**Comment by raisezhang** [comment]
Try to specify the latest version.

for example:   ``` "react-drag-listview": "^0.1.7" ```

**Comment by andrewkazan** [comment]
Thanks man:) it's working
