### ISSUE TITLE
babel-runtime 需要在 pkg.json 中的 deps 申明版本

### ISSUE THREAD

**Issue by pigcan** [raisezhang/react-drag-listview#44]
目前该包对 babel-runtime 有依赖，一旦有依赖需要把 babel-runtime 加入到 pkg 的 dependencies 中。

**Comment by raisezhang** [comment]
react-drag-listview  依赖了  rc-tools 

rc-tools  依赖了  @babel/core
 
@babel/core 依赖了  babel-runtime
 
所以不需要手动声明

**Comment by pigcan** [comment]
rc-tools 是 dev-deps，而 rc-tools 对你的代码编译之后，babel 会给你添加 babel-runtime 的依赖，而 babel-runtime 此时是作为项目依赖的，而不是开发依赖，所以要把 babel-runtime 引入到 deps 中，这是常规的处理，你也可以看看老版本对于 babel 对于 babel-runtime 的文档解释（babel-runtime 需要写入到 deps）。

**Comment by pigcan** [comment]
给你个官方参考 https://unpkg.com/rc-field-form@1.0.1/package.json

**Comment by raisezhang** [comment]
https://github.com/raisezhang/react-drag-listview/commit/4f38c4a69714b469f1194a68338ae49bc9aa572a

添加了

**Comment by raisezhang** [comment]
看下如果没其它问题  我 pub 了

**Comment by pigcan** [comment]
> 看下如果没其它问题 我 pub 了

记得发布. XD

**Comment by raisezhang** [comment]
可以了    抱歉忘了
