### ISSUE TITLE
issue on onDragEnd function

### ISSUE THREAD

**Issue by tonieraco** [raisezhang/react-drag-listview#47]
Hi

I'm using react-drag-listview module with success but in some cases inside the "onDragEnd"  function I receive the error caused by target.parent is undefined:

 target.parentNode.ondragenter = null;
 target.parentNode.ondragover = null;   

is it possibile that target exist and target.parentNode not exist?
con you insert a check?

thanks in advance

Gabrino

**Comment by raisezhang** [comment]
Can you give me a reproducible demo? For CodePen or others, you can fork this demo faster, https://codepen.io/raisezhang/pen/MmjypX

**Comment by raisezhang** [comment]
This usage should not be supported. Drag and drop only supports sorting within the list, and it is not currently supported outside the list.
🙁

**Comment by tonieraco** [comment]
I will change my logic
thanks 😉
