### ISSUE TITLE
当我有列宽度移动时，列拖拽不能先屏蔽会冲突，宽度在动，列拖拽也在响应。

### ISSUE THREAD

**Issue by mar105** [raisezhang/react-drag-listview#48]
当我有列宽度移动时，列拖拽不能先屏蔽会冲突，宽度在动，列拖拽也在响应。

**Comment by mar105** [comment]
列宽度拖动我是用的 ResizeableTitle，网上的例子。

**Comment by mar105** [comment]
或者可以设置设置拖动区域。

**Comment by raisezhang** [comment]
可以自定义拖拽节点 handleSelector ， 比如你在  theader 的 th 里面加一个 90% 的 .drag-th  之类的 div，这样应该可以解决你的问题
