### ISSUE TITLE
codepen demo not working anymore

### ISSUE THREAD

**Issue by abenhamdine** [raisezhang/react-drag-listview#5]
Hi,

Thx for this module !

Just to tell you that your codepen doesn't work anymore because of antd@3<>react@16 breaking changes : 
https://codepen.io/raisezhang/pen/MoMoyz

In order to keep on the codepen working with antd@2, you have to change the following asset : 
https://unpkg.com/antd/dist/antd-with-locales.js
by 
https://unpkg.com/antd@2.13.11/dist/antd-with-locales.js

To work with antd@3, the assets should be (in this order) : 
https://unpkg.com/react@16.2.0/umd/react.production.min.js
https://unpkg.com/react-dom@16.2.0/umd/react-dom.production.min.js
https://unpkg.com/moment@2.14.1/min/moment.min.js
https://unpkg.com/antd@3/dist/antd-with-locales.js
https://unpkg.com/react-drag-listview@0.0.9/dist/react-drag-listview.js

**Comment by raisezhang** [comment]
Thank you for feedback, has now been replaced by  antd@2.13.11

**Comment by abenhamdine** [comment]
Thx, it works now.

**Comment by crazyx13th** [comment]
![grafik](https://user-images.githubusercontent.com/8912561/52335570-fded4f80-2a02-11e9-9b11-100dc2fd0200.png)

**Comment by raisezhang** [comment]
It's worked for me!    isn't it worked now?

**Comment by crazyx13th** [comment]
works now! thanks
