### ISSUE TITLE
Ignore fixed columns on Antd Table

### ISSUE THREAD

**Issue by balboFK** [raisezhang/react-drag-listview#53]
Hello, thanks for the library, works really well and the API is very simple.

Is there any way to ignore the fixed columns of an Antd table? I dont want the user to be able to drag the fixed columns and also not be able to drag a normal column to a place where is a fixed column, if he does that, it would break the layout and some internal rules of the table design.

I saw the handleSelector property but i couldn't figure out a way of managing each column, since i have more than 1 fixed column.

**Comment by raisezhang** [comment]
![image](https://user-images.githubusercontent.com/1481983/146706221-feddfba9-eb91-4876-8301-5b50abd1933f.png)

You can use a class name like ```.ant-table-cell-fix-left``` to realize whether you can drag and drop

**Comment by balboFK** [comment]
Hello @raisezhang! Thanks for the reply.
I did as you said and it fixes the issue with being able to drag the fixed columns, but how would I block other columns to be drag past those fixed columns?
I dont want the user to do as the image bellow shows, because when you drag past the column that has a ignoreSelector, the ordering when dragging seems to get lost and the reorder stops working correctly.
I tried with your default example, by just adding the ignore line and it happened.

Dragging name past the fixed column "key". (I dont want the user to be able to do this)
![image](https://user-images.githubusercontent.com/87539237/146755297-94bae909-1e9e-4285-81d5-c6ddd0342409.png)

After drag, the column "key" went out of order with the others.

![image](https://user-images.githubusercontent.com/87539237/146755486-c4564e84-66fc-4a87-a5d0-18b3116dc327.png)

Thanks!

**Comment by raisezhang** [comment]
Use ```nodeSelector```  to solve the problems you encounter. Only select non fixed nodes

**Comment by balboFK** [comment]
Oh, I see now. So I should use it on the ant table header columns instead of the default 'th', and also use the ignoreSelector to ignore fixed nodes, or just use the nodeSelector to get only non fixed nodes?

**Comment by raisezhang** [comment]
Uh, it's roughly like this

You can look at this example: https://codepen.io/raisezhang/pen/OrrGJL

**Comment by balboFK** [comment]
Yeah, that works like a charm. 
The only problem now is just how to block the user from dragging a non fixed row, past a fixed row? Like i showed on the first image, any idea on how to do that?

Prevent this, drag a column past a column that is fixed, in this case, key is fixed:
![image](https://user-images.githubusercontent.com/87539237/146755297-94bae909-1e9e-4285-81d5-c6ddd0342409.png)

**Comment by raisezhang** [comment]
Can you give me a reproducible demo? For CodePen or others, you can fork this demo faster, https://codepen.io/raisezhang/pen/MmjypX

**Comment by vaynevayne** [comment]
note:

```jsx
// bug
   nodeSelector: "th",
    ignoreSelector: ".ant-table-cell-fix-left",

// work
  nodeSelector: "th:not(.ant-table-cell-fix-left)",
   //  ignoreSelector: ".ant-table-cell-fix-left",
```
