### ISSUE TITLE
added types definitions in DefinitelyTyped

### ISSUE THREAD

**Issue by hirohe** [raisezhang/react-drag-listview#54]
I created this package's types definitions [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped), with [this PR](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/58696).

maybe you can check it and review ?

**Comment by raisezhang** [comment]
Thank you, it looks good.
you can submit PR and I will merge it.

**Comment by hirohe** [comment]
okay, after add types definitions to this package, we can remove `@types/react-drag-listview` 😺

**Comment by raisezhang** [comment]
[0.1.9](https://www.npmjs.com/package/react-drag-listview/v/0.1.9)  Published
