### ISSUE TITLE
Dragging Ant-Design transfer items are not draggable

### ISSUE THREAD

**Issue by stanggt3** [raisezhang/react-drag-listview#57]
Unable to drag to re-order the Target list in this demo  [Dragging Ant-Design transfer items](https://codepen.io/opaulochaves/pen/qgeVLR)

It says "Only the items in the 'Target' list are draggable" but on a desktop PC you cannot drag to reorder the items in the list

**Comment by raisezhang** [comment]
https://codepen.io/raisezhang/pen/JjpJOXj
