### ISSUE TITLE
Getting type error while adding children

### ISSUE THREAD

**Issue by rahulretnan** [raisezhang/react-drag-listview#58]
I'm getting this type of error while adding child components.

No overload matches this call.
  Overload 1 of 2, '(props: DragListViewProps | Readonly<DragListViewProps>): ReactDragListView', gave the following error.
    Type '{ children: Element; nodeSelector: string; onDragEnd: (fromIndex: any, toIndex: any) => void; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<ReactDragListView> & Readonly<DragListViewProps>'.
      Property 'children' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<ReactDragListView> & Readonly<DragListViewProps>'.
  Overload 2 of 2, '(props: DragListViewProps, context: any): ReactDragListView', gave the following error.
    Type '{ children: Element; nodeSelector: string; onDragEnd: (fromIndex: any, toIndex: any) => void; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<ReactDragListView> & Readonly<DragListViewProps>'.
      Property 'children' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<ReactDragListView> & Readonly<DragListViewProps>'

**Comment by rahulretnan** [comment]
I have raised PR for the fix [#59](https://github.com/raisezhang/react-drag-listview/pull/59). Please merge this PR and update the package.

**Comment by raisezhang** [comment]
Thanks ~  

Version 0.2.1 has been released.
