### ISSUE TITLE
Unable to make it work with react-resizable

### ISSUE THREAD

**Issue by abenhamdine** [raisezhang/react-drag-listview#6]
Hi,

I tried to make your module work with react-resizable, in order to be able to both resize columns and to drag& drop them, but with no success :(
as you can see in this demo https://codesandbox.io/s/188wonwxxl the drag&drop starts as soon as the user try to resize the header.

The original demo for resizable only antd table is here : http://react-component.github.io/table/examples/column-resize.html

Any idea how to fix it ?

**Comment by raisezhang** [comment]
The main reason is ```react-draggable``` and ```react-drag-listview``` ```onMouseDown``` event conflict, this is the modified [Demo](https://codesandbox.io/s/0pk95j0z2v)  (line 144)，just add ```e.stopPropagation()``` in method ```onResizeStart``` can be achieve!

Hope that help you~

**Comment by abenhamdine** [comment]
Thx you very much !!
I had no idea it would be so simple, I feel myself a little bit stupid... :/

**Comment by raisezhang** [comment]
I am just familiar with the code I write, and have some excellent components, such as Event objects, which can still return to the front end after nesting many layers.   

bless you~
