### ISSUE TITLE
"isTouchScreen" is not working on desktop

### ISSUE THREAD

**Issue by minamichika** [raisezhang/react-drag-listview#64]
I find that in `utils.js`  using `window.navigator.maxTouchPoints` to check if target platform is mobile or not.
```javascript
var isTouchScreen = function isTouchScreen() {
  return window.navigator.maxTouchPoints > 0;
};
```
But with modern notebook, they have touchscreen, so their `window.navigator.maxTouchPoints` are larger than 0.
This will cause `onMouseDown` event cannot `startDrag` on these devices, please fix this.

**Comment by raisezhang** [comment]
Sorry for this problem, forget that there will also be touch mode on the PC. You can use version 0.1.9 first, https://www.npmjs.com/package/react-drag-listview/v/0.1.9

I will take time to see what good solutions are available to fix this problem.

**Comment by raisezhang** [comment]
Version 2.0.0 has fixed this problem.
