### ISSUE TITLE
The table props scroll doesn't work

### ISSUE THREAD

**Issue by tianlizhao** [raisezhang/react-drag-listview#9]
```
<Table
  size="middle"
  // scroll={{ y: 240 }}
  columns={this.columns}
  pagination={false}
  dataSource={data}
/>
```
onDragEnd 的 formIndex 和 toIndex值不对，而且第一条数据是不能拖动的

**Comment by tianlizhao** [comment]
嗯嗯。。刚查到问题，，准备提个PR, 找没半天，没搞懂当时为什么要 - 1， target.rowIndex 如果有thead 里有tr, 虽然不同级，但取到的rowIndex也会算上，加上scroll就没有thead了。我改了下

**Comment by raisezhang** [comment]
恩  多谢 PR， 单独判断是否 TR 是因为 Table 的使用场景会比较多，所以没有通过 indexOf dom 的方式，因为 rowIndex 性能方面会好于 indexOf Dom

至于PR的版本，是可以解决这个问题，且兼容性也比较好，  容我再想想还有没有其他更好的方案  ^_^   

Thanks

**Comment by raisezhang** [comment]
Has been merged, Thanks PR
